apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  serviceAccountName: test
  containers:
   - name: example
     image: gcr.io/cloud-builders/gsutil
     command: ["sleep", "3600"]
    #  ports:
    #     - containerPort: 80
