server:
  port: 8080

spring:
  application:
    name: api-persona
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${host:localhost}:${port:3306}/${database:demobd}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username:root}
    password: ${password:toor}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  tracing:
    enabled: ${TRACE_ENABLED:false}
    propagation:
      type: ${TRACE_PROPAGATION_HEADER:B3} # B3_MULTI # B3 # W3C
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${TRACER_URL:http://localhost:9411/api/v2/spans}


# logging:
#   pattern:
#     level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"